version: "3.8"

services:
  app:
    image: localhost/fastapi-app:latest
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3-slim"
    userns_mode: keep-id
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ../:/workspace:cached
    environment:
      TZ: Asia/Taipei
